#!/bin/bash
# ~/Projects/st8m/tool/setup.sh
# ST8-M 命令行工具安装脚本

# 严格模式
set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BIN_DIR="$HOME/.loacl/bin"
ST8M_BIN="$BIN_DIR/st8m"

echo -e "${BLUE}=== ST8-M CLI Tool Installer ===${NC}"

# 1. 创建 ~/.local/bin
if [ ! -d "$BIN_DIR" ]; then
	echo -e "${YELLOW}Creating $BIN_DIR...${NC}"
	mkdir -p "$BIN_DIR"
else
	echo -e "${GREEN}$BIN_DIR already exists${NC}"
fi

# 2. 添加到 PATH (zsh)
if [ -f "$HOME/.zshrc" ]; then
	if ! grep -q "$BIN_DIR" "$HOME/.zshrc"; then
		echo -e "${YELLOW}Adding $BIN_DIR to PATH in .zshrc...${NC}"
		echo '' >> "$HOME/.zshrc"
		echo '# ST8-M CLI Tool' >> "$HOME/.zshrc"
		echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$HOME/.zshrc"
		echo -e "${GREEN}Updated .zshrc${NC}"
	else
		echo -e "${GREEN}.zshrc already contains $BIN_DIR${NC}"
	fi
fi

# 3. 添加到 PATH (bash)
if [ -f "$HOME/.bashrc" ]; then
	if ! grep -q "$BIN_DIR" "$HOME/.bashrc"; then
		echo -e "${YELLOW}Adding $BIN_DIR to PATH in .bashrc...${NC}"
		echo '' >> "$HOME/.bashrc"
		echo '# ST8-M CLI Tool' >> "$HOME/.bashrc"
		echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$HOME/.bashrc"
		echo -e "${GREEN}Updated .bashrc${NC}"
	else
		echo -e "${GREEN}.bashrc already contains $BIN_DIR${NC} "
	fi
fi

# 4. 生成 st8m 脚本
echo -e "${YELLOW}Generating st8m script...${NC}"

cat > "$ST8M_BIN" << 'EOF'
#!/bin/bash
# ST8-M CLI Tool
# Generated by setup.sh - Do not edit directly

# 项目路径 (安装时自动注入)
PROJECT_ROOT="PROJECT_ROOT_PLACEHOLDER"

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' 

# 超时设置 (秒)
SYNC_TIMEOUT=30

# 显示帮助
show_help() {
	echo -e "${CYAN}ST8-M CLI Tool${NC}"
	echo ""
	echo "Usage: st8m <command> [args]"
	echo ""
	echo "Commands:"
	echo "	note <filename> Create a note in src/content/note/"
	echo "	jot <filename> 	Create a jotting in src/content/jotting/"
	echo "	update 			Sync project to Github (timeout: ${SYNC_TIMEOUT}s)"
	echo "	help 			show this help message"
	echo ""
	echo "Examples:"
	echo "	st8m note L.001-hello		# Create L.001-hello.md"
	echo "	st8m jot E.001-20260213		# Create E.001-20260213.md"
	echo "	st8m Updated				# Push to Archie-Z/st8m"
}

# 创建笔记
cmd_note(){
	local filename="$1"
	if [ -z "$filename" ]; then
		echo -e "${RED}Error: Missing filename${NC}"
		echo "Usage: st8m note <filename>"
		return 1
	fi
	
	local target_dir="$PROJECT_ROOT/src/content/note/zh-cn"
	local filepath="$target_dir/${filename}.md"
	local CURRENT_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

	# 确保目录存在
	mkdir -p "$target_dir"
	
	# 创建文件 (如果不存在)
	if [ ! -f "$filepath" ]; then
		cat > "$filepath" << 'FILEEOF'
---
title:$filename
timestamp:$CURRENT_TIMESTAMP
series:
tags: []
description:
---

FILEEOF
		echo -e "${GREEN}Created: $filepath${NC}"
	else
		echo -e "${YELLOW}File already exists: $filepath${NC}"
	fi

	# 进入目录并打开文件
	cd "$target_dir" || return 1
	echo -e "${BLUE}Now in: $(pwd)${NC}"

	# 尝试用常用编辑器打开
	if command -v nvim &> /dev/null; then
		nvim "$filepath"
	elif command -v vim &> /dev/null; then
        vim "$filepath"
    elif command -v code &> /dev/null; then
        code "$filepath"
    else
        echo -e "${YELLOW}File created. Open manually: $filepath${NC}"
    fi
}

# 创建随笔
cmd_jot() {
    local filename="$1"
    if [ -z "$filename" ]; then
        echo -e "${RED}Error: Missing filename${NC}"
        echo "Usage: st8m jot <filename>"
        return 1
    fi
    
    local target_dir="$PROJECT_ROOT/src/content/jotting/zh_cn"
    local filepath="$target_dir/${filename}.md"
    
    mkdir -p "$target_dir"
    
    if [ ! -f "$filepath" ]; then
        cat > "$filepath" << 'FILEEOF'
---
title:$filename
timestamp:$CURRENT_TIMESTAMP
series:
tags: []
description:
---

FILEEOF
	        echo -e "${GREEN}Created: $filepath${NC}"
    else
        echo -e "${YELLOW}File already exists: $filepath${NC}"
    fi
    
    cd "$target_dir" || return 1
    echo -e "${BLUE}Now in: $(pwd)${NC}"
    
    if command -v subl &> /dev/null; then
        subl "$filepath"
    elif command -v nvim &> /dev/null; then
        nvim "$filepath"
    elif command -v vim &> /dev/null; then
        vim "$filepath"
    elif command -v code &> /dev/null; then
        code "$filepath"
    else
        echo -e "${YELLOW}File created. Open manually: $filepath${NC}"
    fi
}
# GitHub 同步（带超时）
cmd_update() {
    local original_dir
    original_dir=$(pwd)
    
    echo -e "${BLUE}Syncing to GitHub...${NC}"
    echo -e "${YELLOW}Project: $PROJECT_ROOT${NC}"
    echo -e "${YELLOW}Timeout: ${SYNC_TIMEOUT}s${NC}"
    
    cd "$PROJECT_ROOT" || {
        echo -e "${RED}Error: Cannot enter $PROJECT_ROOT${NC}"
        return 1
    }
    
    # 检查是否是git仓库
    if [ ! -d ".git" ]; then
        echo -e "${RED}Error: Not a git repository${NC}"
        cd "$original_dir" || return 1
        return 1
    fi
    
    # 使用timeout命令设置超时
    local sync_failed=0
    
    # 添加所有更改
    echo -e "${CYAN}→ git add .${NC}"
    if ! timeout "$SYNC_TIMEOUT" git add .; then
        echo -e "${RED}Error: git add timeout or failed${NC}"
        sync_failed=1
    fi
    
    # 提交（如果有更改）
    if [ $sync_failed -eq 0 ]; then
        if git diff --cached --quiet; then
            echo -e "${YELLOW}No changes to commit${NC}"
        else
            local timestamp
            timestamp=$(date '+%Y-%m-%d %H:%M:%S')
            echo -e "${CYAN}→ git commit${NC}"
            if ! timeout "$SYNC_TIMEOUT" git commit -m "update: $timestamp"; then
                echo -e "${RED}Error: git commit timeout or failed${NC}"
                sync_failed=1
            fi
        fi
    fi
    
    # 推送
    if [ $sync_failed -eq 0 ]; then
        echo -e "${CYAN}→ git push origin $(git branch --show-current 2>/dev/null || echo 'main')${NC}"
        if ! timeout "$SYNC_TIMEOUT" git push; then
            echo -e "${RED}Error: git push timeout or failed${NC}"
            sync_failed=1
        fi
    fi
    
    # 返回原目录
    cd "$original_dir" || return 1
    
    if [ $sync_failed -eq 1 ]; then
        echo -e "${RED}Sync failed. Returned to: $original_dir${NC}"
        return 1
    else
        echo -e "${GREEN}✓ Sync completed successfully${NC}"
        return 0
    fi
}

# 主入口
main() {
    local cmd="$1"
    shift || true
    
    case "$cmd" in
        note)
            cmd_note "$1"
            ;;
        jot)
            cmd_jot "$1"
            ;;
        update)
            cmd_update
            ;;
        help|--help|-h|"")
            show_help
            ;;
        *)
            echo -e "${RED}Unknown command: $cmd${NC}"
            show_help
            return 1
            ;;
    esac
}

main "$@"
EOF

# 替换项目路径占位符
sed -i "s|PROJECT_ROOT_PLACEHOLDER|$PROJECT_ROOT|g" "$ST8M_BIN"

# 5. 设置可执行权限
chmod +x "$ST8M_BIN"
echo -e "${GREEN}Installed: $ST8M_BIN${NC}"

# 6. 完成提示
echo ""
echo -e "${GREEN}=== Installation Complete ===${NC}"
echo ""
echo -e "To use st8m immediately, run:"
echo -e "${CYAN}  source ~/.zshrc${NC}  # (if using zsh)"
echo -e "${CYAN}  source ~/.bashrc${NC} # (if using bash)"
echo ""
echo -e "Or restart your terminal."
echo ""
echo -e "Quick start:"
echo -e "${CYAN}  st8m note hello-world${NC}"
echo -e "${CYAN}  st8m jot daily-thought${NC}"
echo -e "${CYAN}  st8m update${NC}"